console.log(" == Even Fibonacci numbers == ");
console.log("Problem 2\n");
console.log("Each new term in the Fibonacci sequence is generated by adding the previous two terms." +
    "By starting with 1 and 2, the first 10 terms will be:\n" +
    "\t\t1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...\n" +
    "By considering the terms in the Fibonacci sequence whose values do not exceed four million," +
    "find the sum of the even-valued terms.");

var a = 1, b = 2, c = 1, res = 0;

while (a + b < 4000000) {
    if (c % 2 === 0) {
        res += c;
    }
    c = a + b;
    a = b;
    b = c;
    // console.log(c);
}

console.log(res);